# Generated by Django 4.0.4 on 2022-05-11 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nae:')),
                ('kshf', models.IntegerField(max_length=50, verbose_name='سعر الكشف:')),
                ('timeour', models.IntegerField(max_length=50, verbose_name='مده الانتظار:')),
                ('timemany', models.IntegerField(max_length=50, verbose_name='عدد ساعات العمل :')),
                ('salr', models.IntegerField(max_length=50, verbose_name='سعر المكالمه :')),
                ('tkhss', models.CharField(max_length=50, verbose_name='التخصص :')),
                ('who_i', models.TextField(max_length=50, verbose_name='how')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='are')),
                ('imge', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='img')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
