# Generated by Django 4.0.4 on 2022-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kshf',
            field=models.IntegerField(verbose_name='سعر الكشف:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salr',
            field=models.IntegerField(verbose_name='سعر المكالمه :'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timemany',
            field=models.IntegerField(verbose_name='عدد ساعات العمل :'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timeour',
            field=models.IntegerField(verbose_name='مده الانتظار:'),
        ),
    ]
