# Generated by Django 4.0.4 on 2022-05-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_alter_profile_kshf_alter_profile_salr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='kshf',
        ),
        migrations.AlterField(
            model_name='profile',
            name='salr',
            field=models.IntegerField(null=True, verbose_name='سعر المكالمه :'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timemany',
            field=models.IntegerField(null=True, verbose_name='عدد ساعات العمل :'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timeour',
            field=models.IntegerField(null=True, verbose_name='مده الانتظار:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tkhss',
            field=models.CharField(max_length=50, null=True, verbose_name='التخصص :'),
        ),
    ]
