# Generated by Django 4.0.4 on 2022-05-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0003_remove_profile_kshf_alter_profile_salr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kghsf',
            field=models.IntegerField(null=True, verbose_name='سعر كشفيه:'),
        ),
    ]
