# Generated by Django 4.0.4 on 2022-05-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0004_profile_kghsf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.CharField(max_length=50, null=True, verbose_name='adress :'),
        ),
    ]
